restarted writing of alfs old files moved to bak folder based on lfs-8.3 version-check and preparing first pass done

diff --git a/scripts/alfs b/scripts/alfs
--- a/scripts/alfs
+++ b/scripts/alfs
@@ -1,13 +1,28 @@
 #!/bin/bash
 
 #Parameters check
-if [ $# -lt 4 ]; then echo -e 'Invalid number of parameters! Parameters are:
-1-Working directory
-2-Dependencies CSV file
-3-Packages download URLs file
-4-Number of processors to use
-5-(optional)Starting package to build'; exit 1; fi
-if [ ! -d $1 ]; then sudo mkdir -pv $1 || { echo 'Unable to create working directory:' $1; exit 1; }; fi
+if [ $# -lt 4 ]; then
+    echo -e 'Invalid number of parameters!
+USAGE: alfs wdir deps packs procs [start]
+
+DESCRIPTION:
+alfs is a tool to automate the build of packages.
+based on a csv dependencies file, alfs execute package scripts to build dependencies.
+in the dependencies file, all package scripts on one line must be successfully executed before executing scripts of the next line.
+each package name in dependencies file must match the name of an executable script in the same directory of alfs script.
+the package names in dependencies file must follow this uasge: [#]package[#param]...
+a # character can be inserted at the beginning of the package name in dependencies file to indicate that the script must be executed in the current shell context, otherwise script are executed in a separate shell context.
+many others # can be inserted after the package name to pass parameters to the package script.
+
+PARAMETERS:
+wdir: the working directory where all packages will be built
+deps: the comma-separated-value file that list all packages dependencies and build order
+packs: the package urls file. this file contains all the url of the packages that need to be downloaded. each line must contain the package name followed by a tab character and the download url.
+procs: the number of maximum processors to use
+[start]: the optional starting package in dependencies file'; 
+    exit 1;
+fi
+if [ ! -d $1 ]; then sudo mkdir -v $1 || { echo 'Unable to create working directory:' $1; exit 1; }; fi
 if [ ! -e $2 ]; then echo 'Unable to locate dependencies CSV file:' $2; exit 1; fi
 if [ ! -e $3 ]; then echo 'Unable to locate packages download URLs file:' $3; exit 1; fi
 if [[ ! $4 =~ ^[0-9]+$ ]]; then echo 'Invalid number of processors to use:' $4; exit 1; fi
@@ -29,30 +44,31 @@ start='false' &&
 if [ $# -eq 4 ]; then start='true'; fi &&
 #Download all packages from URLs file if necessary
 if [ $start == 'true' ]; then
-#Creating sources directory where all packages will be downloaded and grant current user full access
-sudo mkdir -pv ${wdir}sources &&
-sudo chown -v $(logname): ${wdir}sources &&
-sudo chmod -v 750 ${wdir}sources &&
-cut -f 2- $3 | tr '\t' '\n' | wget -i - -nc -P ${wdir}sources
+    #Creating sources directory where all packages will be downloaded and grant current user full access
+    sudo mkdir -pv ${wdir}sources &&
+    sudo chown -v $(logname): ${wdir}sources &&
+    sudo chmod -v 750 ${wdir}sources &&
+    cut -f 2- $3 | tr '\t' '\n' | wget -i - -nc -P ${wdir}sources
 fi &&
-#For each column in dependencies file
-column=0 &&
-until [ $column -ge $(columnCount $2) ]
+#For each line in dependencies file
+line=1 &&
+until [ $line -ge $(wc -l $2 | cut -d ' ' -f 1) ]
 do
-	(( column++ )) &&
-	#For each package in column
-	for package in $(cut -d ',' -f $column $2)
-	do
-		#Check if we reached the starting package
-		if [ $package == $5 ]; then start='true'; fi
-		if [ $start == 'true' ]; then
-			#Packages starting with # are run in the current shell context
-			if [[ $package =~ ^# ]]; then cmd=". $(dirname $_)/$(echo $package | cut -d '#' -f 2) $wdir $urls $4 $(echo $package | cut -d '#' -f 3- | tr '#' ' ')"
-			#Others are run in subshell
-			else cmd="$(dirname &_)/$(echo $package | cut -d '#' -f 1) $wdir $urls $4 $(echo $package | cut -d '#' -f 2- | tr '#' ' ')"; fi
-			#Run package script and capture errors
-			$cmd || { echo $package 'script failed!'; exit 1; }
-		fi
-	done
+    #For each package in line
+    for package in $(sed "${line}q;d" $2 | tr ',' ' ')
+    do
+	#Check if we reached the starting package
+	if [ $package == $5 ]; then start='true'; fi
+	if [ $start == 'true' ]; then
+	    #Packages starting with # are run in the current shell context
+	    if [[ $package =~ ^# ]]; then cmd=". $(dirname $_)/$(echo $package | cut -d '#' -f 2) $wdir $urls $4 $(echo $package | cut -d '#' -f 3- | tr '#' ' ')"
+	    #Others are run in subshell (separate shell context)
+	    else cmd="$(dirname &_)/$(echo $package | cut -d '#' -f 1) $wdir $urls $4 $(echo $package | cut -d '#' -f 2- | tr '#' ' ')";
+	    fi
+	    #Run package script and capture errors
+	    $cmd || { echo $package 'script failed!'; exit 1; }
+	fi
+    done &&
+    (( line++ ))
 done &&
 echo 'alfs script success'
